version: '3.3'
services:
  variantmetadata-loader:
    image: dbmi/pic-sure-hpds-etl:LATEST
    environment:
      - HEAPSIZE=4096
      - LOADER_NAME=VariantMetadataLoader
    volumes:
      - ./hpds:/opt/local/hpds
      - ./vcfLoad:/opt/local/hpds/vcfInput/
